permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://fonts.googleapis.com/css?family=Atma:300,400,500,600,700|Fredoka+One"
  title: The Pancake Shop
  description: |
    A small shop created for the viewers and fans of the Queen of Pancakes, which carries pins, stickers and prints designed by Queen of Pancakes.
  rationales:
    typefaces.primary: |
      Atma was chosen because of it's friendly presence. It also comes in varrying weights and has an artsy feel.
    typefaces.secondary: |
      Frederika One was chosen because it has a bolder, stronger, but yet still friendly presence. It is good for buttons and making things stand out.
    colors.primary: |
      The primary colour was chosen because it brings in the Kawaii look and feel. It is cute and child-like and gives off the impression that is needed in the site.
    colors.secondary: |
      The secondary colour ws chosen because it is a bright comlementary colour to the primary colour and will catch people's eyes.
    colors.primary-light: |
      The light version of the primary colour was chosen to be the background for the entire site which gives the impression that it is one big pancake.
    colors.secondary-light: |
      This colour was chosen to be used as a lighter version of the secondary colour if needed.
    colors.accentpurple: |
      This colour was chosen to be an accent pop of colour for the site since it is the oposite colour to the background colour. This means it will stand out well.
    colors.accentpurple-shadow: |
        This colour is chosen to be the darker version of the accent purple colour.
  colors:
    background: "--color-primary-light"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-primary-light"
  layouts:
    default: |
      The default layout should be used on almost every page, it includes the websites primary header and footer.
collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
