title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious actio is required. Tyr not to over use buttons because they should be the primary call-for-action for a screen.
