title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious actio is required. Tyr not to over use buttons because they should be the primary call-for-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      This is the basic button that is used on the banners
    fields:
      - name: text
        type: string
        example: "Shop Now"
      - name: url
        type: url
        example: "/products/"
