title: "Banners"
description: |
  Banners are to be used at the top of pages. Hero banners are for item specific pages and will display new products for that item section. Regular banner will be for the homepage.

patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Stickers, Stickers, Stickers!"
      - name: text
        type: string
        example: "Shop Now"
  hero-banner:
    fields:
      - name: heading
        type: string
        example: "Pins, Pins, Pins!"
      - name: text
        type: string
        example: "Shop Now"
